#进行注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

server:
  port: 8799

spring:
  application:
    name: service-zuul
  jackson:
    date-format: yyyy/MM/dd
    time-zone: GMT+8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#网关配置
zuul:
  routes:
    api-a:
      path: /api-desk/** #访问路径
      service-id: service-desk #跳转的路径 目前是跳转到eureka
    api-b:
      path: /api-employee/** #访问路径
      service-id: service-employee #跳转的路径 目前是跳转到eureka
    api-c:
      path: /api-menu/** #访问路径
      service-id: service-menu #跳转的路径 目前是跳转到eureka
    api-d:
      path: /api-order/** #访问路径
      service-id: service-order #跳转的路径 目前是跳转到eureka
    api-e:
      path: /api-login/** #访问路径
      service-id: service-login #跳转的路径 目前是跳转到eureka
    api-f:
      path: /api-meal/** #访问路径
      service-id: service-meal #跳转的路径 目前是跳转到eureka
    api-g:
      path: /api-pay/** #访问路径
      service-id: service-pay #跳转的路径 目前是跳转到eureka
    api-w:
      path: /api-web/** #访问路径
      service-id: client-web #跳转的路径 目前是跳转到eureka

#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000