server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

spring:
  application:
    name: client-web
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    date-format: yyyy-MM-dd

#开启断路器
feign:
  hystrix:
    enabled: true
